FROM ubuntu:xenial
LABEL maintainer="skinlayers@gmail.com"

ARG VERSION=1.0.10
ARG ZCLASSIC_DEB=zclassic-${VERSION}-1-f94256c-amd64.deb
ARG GITHUB_URL=https://github.com/z-classic/zclassic/releases/download/v${VERSION}/$ZCLASSIC_DEB
ARG ZCLASSIC_DEB_SHA256=1024851baf6d294cd3151d0a5f106ab7b5959fdac804230aff64505899edf6f2
ARG SPROUT_PKEY_NAME=sprout-proving.key
ARG SPROUT_PKEY_URL=https://z.cash/downloads/${SPROUT_PKEY_NAME}
ARG SPROUT_PKEY_SHA256=8bc20a7f013b2b58970cddd2e7ea028975c88ae7ceb9259a5344a16bc2c0eef7
ARG SPROUT_VKEY_NAME=sprout-verifying.key
ARG SPROUT_VKEY_URL=https://z.cash/downloads/${SPROUT_VKEY_NAME}
ARG SPROUT_VKEY_SHA256=4bd498dae0aacfd8e98dc306338d017d9c08dd0918ead18172bd0aec2fc5df82
ARG BUILD_DEPENDENCIES="\
    ca-certificates \
    curl \
"
ARG RUNTIME_DEPENDENCIES="\
    libgomp1 \
"

RUN set -eu && \
    adduser --system --home /data --group zclassic && \
    apt-get update && apt-get -y install --no-install-recommends $BUILD_DEPENDENCIES && \
    curl -L "$GITHUB_URL" -o "$ZCLASSIC_DEB" && \
    echo "$ZCLASSIC_DEB_SHA256  $ZCLASSIC_DEB" > "${ZCLASSIC_DEB}_sha256.txt" && \
    sha256sum -c "${ZCLASSIC_DEB}_sha256.txt" && \
    apt -y install "./${ZCLASSIC_DEB}" && \
    curl -L "$SPROUT_PKEY_URL" -o "$SPROUT_PKEY_NAME" && \
    echo "$SPROUT_PKEY_SHA256  $SPROUT_PKEY_NAME" > "${SPROUT_PKEY_NAME}_sha256.txt" && \
    sha256sum -c "${SPROUT_PKEY_NAME}_sha256.txt" && \
    curl -L "$SPROUT_VKEY_URL" -o "$SPROUT_VKEY_NAME" && \
    echo "$SPROUT_VKEY_SHA256  $SPROUT_VKEY_NAME" > "${SPROUT_VKEY_NAME}_sha256.txt" && \
    sha256sum -c "${SPROUT_VKEY_NAME}_sha256.txt" && \
    rm \
        "$ZCLASSIC_DEB" \
        "${ZCLASSIC_DEB}_sha256.txt" \
        "${SPROUT_PKEY_NAME}_sha256.txt" \
        "${SPROUT_VKEY_NAME}_sha256.txt" && \
    apt-mark manual $RUNTIME_DEPENDENCIES && \
    apt-get purge -y --auto-remove $BUILD_DEPENDENCIES $(apt-mark showauto) && \
    apt-get -y install $RUNTIME_DEPENDENCIES && \
    rm -r /var/lib/apt/lists/*

COPY ./docker-entrypoint.sh /

RUN chmod 0755 /docker-entrypoint.sh

USER zclassic

RUN mkdir -m 0700 /data/.zcash-params && \
    ln -s "/${SPROUT_PKEY_NAME}" "/data/.zcash-params/${SPROUT_PKEY_NAME}" && \
    ln -s "/${SPROUT_VKEY_NAME}" "/data/.zcash-params/${SPROUT_VKEY_NAME}" && \
    mkdir -m 0700 /data/.zclassic && \
    { \
        echo 'addnode=139.59.230.86'; \
        echo 'addnode=52.53.125.97'; \
        echo 'addnode=13.91.45.250'; \
        echo 'addnode=136.243.50.159'; \
        echo 'addnode=149.56.135.165'; \
        echo 'addnode=188.2.135.254'; \
        echo 'addnode=74.105.45.225'; \
        echo 'addnode=213.185.254.158'; \
        echo 'addnode=87.103.195.162'; \
        echo 'addnode=68.234.31.67'; \
        echo 'addnode=78.94.32.196'; \
        echo 'addnode=158.69.183.22'; \
        echo 'addnode=120.27.230.83'; \
        echo 'addnode=54.84.135.119'; \
        echo 'addnode=138.68.48.247'; \
        echo 'addnode=89.142.65.151'; \
        echo 'addnode=198.100.147.192'; \
        echo 'addnode=45.77.142.139'; \
        echo 'addnode=60.170.218.192'; \
        echo 'addnode=79.98.144.29'; \
        echo 'addnode=217.182.79.13'; \
        echo 'addnode=37.187.167.145'; \
        echo 'addnode=94.177.229.186'; \
        echo 'addnode=70.64.195.108'; \
        echo 'addnode=66.165.18.187'; \
        echo 'addnode=82.255.125.219'; \
        echo 'addnode=88.99.199.93'; \
        echo 'addnode=173.35.102.85'; \
        echo 'addnode=70.15.71.167'; \
        echo 'addnode=91.218.12.63'; \
        echo 'addnode=74.110.198.76'; \
        echo 'addnode=184.4.139.219'; \
        echo 'addnode=188.212.139.28'; \
        echo 'addnode=36.71.19.104'; \
        echo 'addnode=73.109.223.215'; \
        echo 'addnode=176.209.190.113'; \
        echo 'addnode=108.28.94.150'; \
        echo 'addnode=142.129.143.47'; \
        echo 'addnode=89.207.90.10'; \
        echo 'addnode=82.137.53.24'; \
        echo 'addnode=104.207.149.241'; \
        echo 'addnode=174.52.17.14'; \
        echo 'addnode=77.120.182.170'; \
        echo 'addnode=91.215.188.165'; \
        echo 'addnode=95.161.166.210'; \
        echo 'addnode=76.169.57.92'; \
        echo 'addnode=173.178.209.25'; \
        echo 'addnode=138.197.199.86'; \
        echo 'addnode=188.13.16.230'; \
        echo; \
        echo 'rpcport=8232'; \
        echo 'exportdir=/data'; \
    } > /data/.zclassic/zclassic.conf && \
    chmod 0600 /data/.zclassic/zclassic.conf

VOLUME ["/data"]

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/bin/zcashd", "-printtoconsole", "-disabledeprecation=1.0.10-1"]
